<!DOCTYPE html>
<html>
<head>
<meta name="login" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="css/main.css">
</head>
<body>



<nav class="nav1"><!-- nav menu -->
	<div> Health Status&#128578 </div> 
	<a href="serverstatus.html">Server Status</a>
    <a href="logsearch.html">Log Search</a>
	<a href="firewall.html">Firewall Settings</a>
	<div class="nav2">
		<a href="logsearch.php">Edit User</a>
		<a href="login.html">Logout</a>
	</div>
</nav>
</body>
</html>