version: '3.8'
services :
  web:
    # This image is for Apache, we may want to change it, may not
    build: ../Portal
    container_name: web-server
    #expose:
      #- "80:80"
      #- "443:443"
    #env_file:
    #- ./opt/secrets.env

  ubuntu:
    build: ../Web-Application-Firewall
    container_name: web-application-firewall
    #env_file:
    #- ./opt/secrets.env
    environment:     #connection string for db... move to .env eventually (format mongodb://{USERNAME}:{PASSWORD}@{DATABASE})
      - MONGODB_CONNSTRING=mongodb://root:group41@database

  mongodb:
    image: mongo
    container_name: database
    command:
      - mongod
      - ./import.sh
    environment:     #Note to selves to change this on delivery, possible done as .env variable folder
      #- .env
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=group41
      - MONGODB_CONNSTRING=mongodb://root:group41@database
    volumes:
      #- ../Database/mongod.conf:/etc/mongod.conf:ro
      - ../Database/init:/docker-entrypoint-initdb.d
      - ../Database/seed:/seed
      - db:/data/db
    ports:
      - "27017:27017" #This is mongo default port, would recommend changing this
    expose: #may or may not do anything
      - "27017"
    #env_file:
      #- ./opt/secrets.env


volumes:
    db:
