version: '3.8'

services:

  web_application_firewall:
    build: ../web_application_firewall
    image: owasp/modsecurity:nginx-alpine
    container_name: web_application_firewall
    ports:
      - "8000:80"
    depends_on:
      - webgoat
    volumes:
      - ../web_application_firewall/nginx.conf:/etc/nginx/templates/nginx.conf.template:rw
      - ../portal/www:/usr/share/nginx/html:rw
    environment:     #connection string for db... move to .env eventually (format mongodb://{USERNAME}:{PASSWORD}@{DATABASE})
     - MONGODB_CONNSTRING=mongodb://root:group41@database
    networks:
      projectNetwork:
        ipv4_address: 172.2.2.4

  mongodb:
    image: mongo
    container_name: database
    command:
      - mongod
    environment:     #Note to selves to change this on delivery, possible done as .env variable folder
      #- .env
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=group41
      - MONGODB_CONNSTRING=mongodb://root:group41@database
    volumes:
      #- ../database/mongod.conf:/etc/mongod.conf:ro
      - ../database/init:/docker-entrypoint-initdb.d
      - ../database/seed:/seed
      - db:/data/db
    ports:
      - "27017:27018" #This is mongo default port, would recommend changing this
    expose: #may or may not do anything
      - "27017"
    networks:
      projectNetwork:
         ipv4_address: 172.2.2.3


  webgoat:
    build: ../webgoat
    image: webgoat/webgoat-8.0
    container_name: webgoat
    ports:
      - "8080:8080"
    #env_file:
      #- ./opt/secrets.env
    networks:
      projectNetwork:
        ipv4_address: 172.2.2.5

volumes:
  db:

networks:
  projectNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.2.2.0/28"
