version: '3.8'
services:

  web_application_firewall:
    build: ../web_application_firewall
    image: owasp/modsecurity:nginx-alpine
    container_name: web_application_firewall
    ports:
      #- "7999:8080"
      - "8000:8000"
      - "80:80"
      #- "30:30"
    expose:
      - "8000"
      - "443"
      - "80"
      - "30"
    depends_on:
      - webgoat
    environment:     #connection string for db
      - MONGODB_CONNSTRING=mongodb://root:group41@database
    volumes:
      - ../web_application_firewall/app/templates:/templates:rw
      - ../web_application_firewall/app/static:/static:rw
      - ../web_application_firewall/etc/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:rw
      - ../web_application_firewall/etc/modsecurity.d/setup.conf:/etc/nginx/templates/modsecurity.d/setup.conf.template:rw
      #- ../web_application_firewall/etc/modsecurity.d/:/etc/modsecurity.d/:rw #REMOVE THIS, JUST FOR TESTING
    networks:
      projectNetwork:
        ipv4_address: 172.2.2.4

  mongodb:
    image: mongo
    container_name: database
    environment:     #Note to selves to change this on delivery, possible done as .env variable folder
      #- .env
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=group41
      - MONGODB_CONNSTRING=mongodb://root:group41@database
    volumes:
      - db:/data/db
      - ../database/seed:/seed
      - ../database/init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
      - "27018:27018"
      #This is mongo default port, would recommend changing this
    expose: #may or may not do anything
      - "27017"
      - "27018"
    networks:
      projectNetwork:
        ipv4_address: 172.2.2.3

  webgoat:
    build: ../webgoat
    image: webgoat/webgoat-8.0
    container_name: webgoat
    ports:
      - "8080:8080" #IM PRETTY SURE THIS SHOULD JUST BE EXPOSED, NOT EXTERNAL
    #env_file:
      #- ./opt/secrets.env
    networks:
      projectNetwork:
        ipv4_address: 172.2.2.5


volumes:
    db:


networks:
  projectNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.2.2.0/28"
