version: '3.8'
services:

  web_application_firewall:
    build: ../web_application_firewall
    image: owasp/modsecurity:nginx-alpine
    container_name: web_application_firewall
    ports:
      - "7999:8080"
      - "8000:8000"
      - "80:80"
    expose:
      - "8000"
      - "443"
      - "80"
    depends_on:
      - webgoat
    volumes:
      - ../web_application_firewall/nginx.conf:/etc/nginx/templates/nginx.conf.template:rw
      - ../portal/www:/usr/share/nginx/html:rw
    environment:     #connection string for db... move to .env eventually (format mongodb://{USERNAME}:{PASSWORD}@{DATABASE})
      - MONGODB_CONNSTRING=mongodb://root:group41@database
    networks:
      projectNetwork:
        ipv4_address: 172.2.2.4

  # web:
  #   # This image is for Apache, we may want to change it, may not
  #   build: ../Portal
  #   container_name: web-server
  #   networks:
  #     projectNetwork:
  #       ipv4_address: 172.2.2.4
  #   #expose:
  #     #- "80:80"
  #     #- "443:443"
  #   #env_file:
  #   #- ./opt/secrets.env


  mongodb:
    image: mongo
    container_name: database
    environment:     #Note to selves to change this on delivery, possible done as .env variable folder
      #- .env
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=group41
      - MONGODB_CONNSTRING=mongodb://root:group41@database
    volumes:
      #- ../Database/mongod.conf:/etc/mongod.conf:ro
      - db:/data/db
      - ../Database/seed:/seed
      - ../Database/init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
      - "27018:27018"
      #This is mongo default port, would recommend changing this
    expose: #may or may not do anything
      - "27017"
      - "27018"
    networks:
      projectNetwork:
        ipv4_address: 172.2.2.3


  webgoat:
    build: ../webgoat
    image: webgoat/webgoat-8.0
    container_name: webgoat
    ports:
      - "8080:8080"
    #env_file:
      #- ./opt/secrets.env
    networks:
      projectNetwork:
        ipv4_address: 172.2.2.5

volumes:
    db:

networks:
  projectNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.2.2.0/28"